### ISSUE TITLE
Copy text without anafora

### ISSUE THREAD

**Issue by EgoLaparra** [bethard/anaforatools#2]
Could there be an option to extract the text from timebanq  and create the folder structure when there are no anafora files?

**Comment by bethard** [comment]
There is something like that in anafora.timeml:
https://github.com/bethard/anaforatools/blob/master/anafora/timeml.py#L91
But it would be nice to have something like that for plain text files that just moves them into their expected Anafora locations.

**Comment by EgoLaparra** [comment]
If we are going to push the annotations for the practice phase to the competition repository, we don't really need this feature right now.

**Comment by EgoLaparra** [comment]
Solved by https://github.com/bethard/anaforatools/pull/3
